clear all
close all


%% Initialization
% initializes simulation parameters and generates the structure prmQAMTxRx. 
prmQAMTxRx = system_init; % QAM system parameters 



coder.extrinsic('createScopes','runScopes','releaseScopes')

    QAMTx = QAMTransmitter(...
        'UpsamplingFactor', prmQAMTxRx.Upsampling, ...
        'ModulationOrder', prmQAMTxRx.M, ...
        'FrameSize', prmQAMTxRx.FrameSize,...
        'TransmitterFilterCoefficients',prmQAMTxRx.TransmitterFilterCoefficients);

    QAMChan = Channel('PhaseOffset', prmQAMTxRx.PhaseOffset, ...
        'SignalPower', 1/prmQAMTxRx.Upsampling, ...
        'UpsamplingFactor', prmQAMTxRx.Upsampling, ...
        'EbNo', prmQAMTxRx.EbNo, ...
        'BitsPerSymbol', prmQAMTxRx.M, ...
        'FrequencyOffset', prmQAMTxRx.FrequencyOffset, ...
        'SampleRate', prmQAMTxRx.Fs);
 
    QAMRx = QAMReceiver('DesiredAmplitude', 1/sqrt(prmQAMTxRx.Upsampling), ...
        'ModulationOrder', prmQAMTxRx.M, ...
        'DownsamplingFactor', prmQAMTxRx.Downsampling, ...
        'PhaseRecoveryDampingFactor', prmQAMTxRx.PhaseRecoveryDampingFactor, ...
        'PhaseRecoveryLoopBandwidth', prmQAMTxRx.PhaseRecoveryLoopBandwidth, ...
        'TimingRecoveryDampingFactor', prmQAMTxRx.TimingRecoveryDampingFactor, ...
        'TimingRecoveryLoopBandwidth', prmQAMTxRx.TimingRecoveryLoopBandwidth, ...
        'TimingErrorDetectorGain', prmQAMTxRx.TimingErrorDetectorGain, ...
        'PostFilterOversampling', prmQAMTxRx.Upsampling/prmQAMTxRx.Downsampling, ...
        'SampleRate', prmQAMTxRx.Fs, ...
        'ReceiverFilterCoefficients', prmQAMTxRx.ReceiverFilterCoefficients);    
%  
     QAMScopes = createScopes;

t(1) = 0;
while(1)
    transmittedSignal = step(QAMTx); % Transmitter
    
    corruptSignal = step(QAMChan,transmittedSignal);

    [RCRxSignal,frequencyOffsetCompensate,timingRecBuffer,ProcessConstellation,temp] = step(QAMRx,corruptSignal); % Receiver
    t = [1:length(temp)]*prmQAMTxRx.Ts + t(end);
    plot(t,mod(temp,pi/2))
    hold on
    plot(t,mod(-2*pi*prmQAMTxRx.FrequencyOffset*t - prmQAMTxRx.PhaseOffset,pi/2),'r')
    hold off

    stepScopes(QAMScopes,RCRxSignal,frequencyOffsetCompensate,timingRecBuffer,ProcessConstellation); % Plots all the scopes
    
end

